### ISSUE TITLE
has_input usage description and range edits

### ISSUE THREAD

**Issue by RLovering** [geneontology/annotation_extensions#21]
I think  'or a cellular response process involved in the gene product's participation in a molecular function or biological process'  should be deleted from the current usage statement: 
- Identifies an entity affected by (bound, transported, modified, consumed or destroyed), or a cellular response process involved in the gene product's participation in a molecular function or biological process. There is no requirement for the gene product being annotated to physically interact with the entity identified. Cases where this relation should be used include where there is insufficient evidence to suggest the gene product and entity directly interact or when the entity is an input to a biological process but doesn't physically interact with the gene product being annotated.

There are no annotations where cellular response GO term is included in C16 with a has_input relationship. All GO terms in C16 with this relationship are complex/component terms. If someone wanted to make this sort of extension I think they would use part_of (but haven't thought of all possiblities here)

The local range should also be updated so that u'GO:0051716': u'cellular response to stimulus', is removed

**Comment by dosumis** [comment]
#28

[doc for version being discussed](https://github.com/geneontology/annotation_extensions/blob/50e4cb3d3c098275fb347ef62d32ad2cd7aadf5f/doc/has_input.md)

**Comment by dosumis** [comment]
The use of has_input with cellular response follows established patterns used in the ontology.

Usage statement should probably be simplified with details of types of usage split out into examples.

**Comment by RLovering** [comment]
I think you have got your domain and ranges mixed up.
I would suggest that GO:0051716': u'cellular response to stimulus is one of the local domains within the BFO:0000007 'domain'. But that the range 'has_input" would be a chemical or protein etc. and would not include a cellular response term.

So for example the GO term GO:0044381   glucose import in response to insulin stimulus is a part_of GO:0032869 cellular response to insulin stimulus.

Unless you are suggesting that people could create
Regulation of transcription AE has_input cellular response to carbohydrate has_input glucose 
I think this type of extension is probably too complex for C16 and only acheivable with LEGO.
I would prefer 
protein X IDA Regulation of transcription AE part_of cellular response to carbohydrate
protein X IDA cellular response to carbohydrate AE has_input glucose

**Comment by dosumis** [comment]
Hi Ruth,

You're right.  It's nonsense to have this in the range.  I have removed it.  The usage statement needs to be more generally updated too.  Given arguments about this relation in the past I've been avoiding rewriting but decided to bite the bullet.  How's this:

Use this relation to relate a biological process or molecular function to an entity that participates in the process/function, is present at the start of the process/function and whose state is affected by that process/function.  Change of state includes being transported, modified, consumed or destroyed.  An input may be any continuant: chemical; gene product; cell component;  cells type; organism.  For inputs to MFs that are bound by the gene product that executes the MF, the more specific relation 'has_direct_input' may be used.

formal def in RO updated to:

p has direct input c iff c is a participant in p, c is present at the start of p, and the state of c is modified during p.

(was formerly on a relation called has_direct_input, but whose intention was different from the one of the same name used in AEs)

Cheers,
David

**Comment by RLovering** [comment]
Hi David

I think that this usage statement looks good. However, I think that has_input (and has_direct_input, in_presence_of, dependent_on) is also used to extend cellular response terms.

Ie GO:0044344 cellular response to fibroblast growth factor stimulus has_input FGF1

FGF1 is not necessarily changed by involvement in the process.

Have just looked at the has_agent usage etc information and realised that this is not an appropriate relationship to use instead?

Ruth

**Comment by dosumis** [comment]
Good point. We actually use has_input to define response terms in the ontology.  This usage is consistent with a different, simpler proposed definition: a participant that is present at the start of the process. 

CC @cmungall @ukemi
