### ISSUE TITLE
has_output definition

### ISSUE THREAD

**Issue by RLovering** [geneontology/annotation_extensions#22]
Please revise definition to:
p has direct output c if c is a participant in p, c is present at the end of p, and c is not present at the beginning of c.
[change input to output and iff to if]
- Current definition: p has direct input c iff c is a participant in p, c is present at the end of p, and c is not present at the beginning of c.

**Comment by dosumis** [comment]
#28

**Comment by dosumis** [comment]
Fixed in RO.
