### ISSUE TITLE
occurs_in definition - revise

### ISSUE THREAD

**Issue by RLovering** [geneontology/annotation_extensions#25]
Not sure exactly how to revise this but there needs to be more consistency, ie all 'letters' should be defined, 't' is not. And it needs to be written so that it makes sense, more punctuation might help.

Note weird characters imported into github page 

remove =def  as in the definitions I have seen so far this phrase not present
What is:
t, time?
s, spatial regions?
sa, ?

I cannot understand this sufficiently to suggest any edits:

b occurs_in c =def b is a process and c is a material entity or immaterial entity& there exists a spatiotemporal region r and b occupies_spatiotemporal_region r.& forall(t) if b exists_at t then c exists_at t & there exist spatial regions s and sâ�� where & b spatially_projects_onto s at t& c is occupies_spatial_region sâ�� at t& s is a proper_continuant_part_of sâ�� at t

Note the usage example is much easier to understand:
Usage
Identifies the cell, tissue, cellular component or anatomical entity within which all parts of the molecular function or biological process occurs

**Comment by dosumis** [comment]
#28

**Comment by dosumis** [comment]
Weirdness (beside character encoding) looks like an attempt to comply with draft BFO 2.  Agree it is incomprehensible. 

CC @cmungall  - Are you happy with redrafting, removing temporal quantification and assuming spatial location is always relative?

**Comment by cmungall** [comment]
@jamesoverton, we made the defs of some ro/core primitives more user-friendly, e.g. part-of, was there a reason we didn't do the same for occurs-in?
