### ISSUE TITLE
regulates_o_results_in_maturation_of - subsets required

### ISSUE THREAD

**Issue by RLovering** [geneontology/annotation_extensions#30]
please add subsets for P2G: AE_cellular_component, AE_cell_or_anatomical
Sorry there are going to be alot of these, it was difficult to look at the table of subsets and consider these without having the domais/ranges information. 
Rachael and I will submit individual tickets for each one

**Comment by dosumis** [comment]
Working on adding range for regulates_o development relations. New release coming soon. No need for individual tickets.
