### ISSUE TITLE
results_in_movement_of - change of range

### ISSUE THREAD

**Issue by RLovering** [geneontology/annotation_extensions#34]
There is a big difference between the results_in_movement_of wiki page and the information on the gorel_edits.obo file.

Specifically on the wiki the range is:cell or cellular component 
whereas the gorel_edits.obo file only has the range: cell.
Furthermore the gorel_edits.obo file Usage is:
Use this relation to link a locomotion process to the type of cell or anatomical structure or organism that the process results in locomotion of.

So at the very least the range needs to also include: { u'WBbt:0005766': u'Anatomy', u'PO:0009012': '', u'UBERON:0001062': u'anatomical entity', u'PO:0025131': u'plant anatomical entity'}
But I also think that u'GO:0005575': u'cellular_component', should be added, to cover the movement of cilia? As these won't use the 'transports' relationship. Although possibly a new term should just be requested if this AE relationship is required?

With the above change the P2G subsets maybe should be included: AE_GO:cellular_component.

The regulates_o_results_in_movement_of will need to be edited to follow the decision made above:
range currently includes cellular component, (keep or delete?) as well as the cell ontologies, but will need { u'WBbt:0005766': u'Anatomy', u'PO:0009012': '', u'UBERON:0001062': u'anatomical entity', u'PO:0025131': u'plant anatomical entity'} Not sure if plant tissues/organs move?

Plus P2G subsets should be included:
AE_cell_or_anatomical (and maybe AE_GO:cellular_component).

Thanks

Ruth

**Comment by dosumis** [comment]
Wiki version is out of date. gorel is now more closely aligned with usage in GO. RO needs to catch up.
- Agree that local range needs to bring in terms from other ontologies, although this is really a failure of infrastructure as should be able to do this using standard inter-ontology mappings. For now we should doc standard sets e.g for cell, set should include IDs from CL WBbt etc.
- Interesting point about movement of cilia. Need to be aligned with ontology here.

**Comment by dosumis** [comment]
Ontology is poorly axiomatised wrt cillium movement.  Here's the relevant branch:

![image](https://cloud.githubusercontent.com/assets/112839/8327705/57b77914-1a62-11e5-9d70-a48757db167d.png)

There are some terms in this branch that are also in the transport branch:

e.g. 

![image](https://cloud.githubusercontent.com/assets/112839/8327792/0ae79924-1a63-11e5-9940-be60b8748adb.png)
