### ISSUE TITLE
Urgent - occurs_in local domain

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/annotation_extensions#47]
Hi,

The local domain for occurs_in doesn't appear to be correct any more. It used to be BFO:0000007 process (to be interpreted as any MF or BP), but now it has been changed to BFO:0000003 occurrent (not sure what this is in GO terms).

This is causing _many_ annotations to be flagged as wrong.

Could you please take a look and see if this needs changing?

Thanks,
Rachael.

**Comment by dosumis** [comment]
Hmmm.   BFO:0000003 occurrent is correct. It follows what's in OWL:domain in RO.  Here's the heirarchy (process is BFO_0000015 not 7):

![image](https://cloud.githubusercontent.com/assets/112839/8405095/00722776-1e4a-11e5-994a-c91fded10565.png)

It allows for events as well as processes to be recorded as occuring in some location/structure.  

As we don't have events in GO, I'll change local domain to  BFO_0000015 now.  But I need to know why choosing a more general class for local_domain is causing annotations to be flagged as wrong.  This makes no sense to me.  Perhaps the checking process is using a (very) outdated BFO?

CC @cmungall @hdietze

**Comment by dosumis** [comment]
Hi Rachael, 

Can you clarify where the checks are failing.  Is it Jenkins, QuickGO, protein2GO ?

Cheers,
David

**Comment by dosumis** [comment]
Update: Traced problem to BFO:GO mapping table used by QuickGO webservices.  Tony has now updated this to use BFO:0000015.  This is a temporary solution, pending switch to use of ontology with mapping.
