### ISSUE TITLE
secreted_from or secreted_by relationship

### ISSUE THREAD

**Issue by RLovering** [geneontology/annotation_extensions#49]
from Barcelona meeting:
Clarification: Extracellular matrix is not part of a cell, therefore when adding cell type information to C16 (to extend an extracellular matrix annotation) this should use the relationship adjacent_to or secreted_from, not part_of. However, adjacent_to and secreted_from are not C16 relationships yet.
ACTION: Confirm that these RO relationships are to be included in the C16 relationship file (David OS)
#48

**Comment by dosumis** [comment]
Seems we do not have 'secreted by' in RO.  'produced by' (see #48) may be sufficient.

**Comment by dosumis** [comment]
Adjacent to is in GOREL with relevant subsets, but needs local domain and range.

**Comment by dosumis** [comment]
For adjacent_to, I've added:

local_range: cell cellular_component
local_domain: cellular_compoment

Please yell if you'd like more.

Will be visible in docs following update (pending).

**Comment by dosumis** [comment]
BUT:  

adjacent_to:
definition "x adjacent to y if and only if x and y share a boundary"  !!!!

@cmungall does this really track usage?

**Comment by cmungall** [comment]
+1 to produced_by

adjacency usage: not sure about usage in annotation extensions, many CC definitions are kind of labile anyway. But usage within CC seems consistent

**Comment by dosumis** [comment]
'Shares a boundary with' looks too strong.  Esp for suggested usage for ECM close to some cell.

**Comment by cmungall** [comment]
What separates the metazoan ECM and the cell?

**Comment by dosumis** [comment]
On 7 Aug 2015 21:07, "Chris Mungall" notifications@github.com wrote:

> What separates the metazoan ECM and the cell?

That's not a problem. But what about annotation to some ECM component?

**Comment by dosumis** [comment]
adjacent_to now in doc.
