### ISSUE TITLE
causually upstream of page missing

### ISSUE THREAD

**Issue by RLovering** [geneontology/annotation_extensions#50]
Hi David
please could you create a page for causually upstream of
there is a wiki page for this relation: http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:causally_upstream_of but I couldn't see it listed in the docs index
Thanks
Ruth

**Comment by cmungall** [comment]
I'm not sure this is required, see my comments on the noctua list

**Comment by RLovering** [comment]
Please could you add what ticket/page/list you are refering to

**Comment by rachhuntley** [comment]
It would be good to get this page over in any case, even if it is deprecated, as there is a lot of documentation on it, which would be a shame to lose;
http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:causally_upstream_of

**Comment by dosumis** [comment]
Doc up now up-to-date.  @cmungall  Please could you link to noctua discussion of why this should not be used in AE give a brief outline here.  Is this to be replaced by MF->MF relations in LEGO?

**Comment by dosumis** [comment]
Closing now.  We can create a separate ticket if more discussion of this relation is required.
