### ISSUE TITLE
Relation to specify cell types for "cell-cell" terms

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/annotation_extensions#61]
Hi,

I'm opening this as a ticket as there are lots of side discussions happening, so to keep everything together.

The original issue is how to specify the cell types involved when annotating to a cell-cell-type term, e.g. cell-cell adhesion or cell-cell signaling.

It has been suggested that has_participant is the correct relation, but this relation has for a long time been dis-allowed for use in annotation extensions, partly because of it's potential to be mis-used when a more appropriate child relation should be used, but there may have been other reasons for this that I'm unaware of (Chris M. can probably shed some light on this).

I’m not sure that the existing has_participant should be used for the cell-cell annotations, I would want it to be restricted so that only cell types can be used and only for cell-cell terms (to prevent its mis-use), but the child relations (has_input, has_output etc.) have local ranges for chemical, complex and gene product - so I don't think this restriction could be applied to has_participant.

Would it make sense to create a child relation of has_participant specific for these use cases, e.g. "has_participant_cell" that would only be appropriate for use with cell-cell type terms?

Rachael.

@cmungall @dosumis @RLovering @rebeccafoulger

**Comment by cmungall** [comment]
@dosumis has done some work on cell-cell signaling.

has_participant_cell doesn't communicate anything beyond has_participant, if the filler class is a cell type.

There are some interesting issues here. How do you say it's two cells of the same type? Adding two assertions won't work, as these are treated as semantically identical, and we deliberately steered away from allowing cardinality in extensions.

**Comment by rachhuntley** [comment]
So would it be more sensible for us to request the specific GO terms that we want? e.g. we recently requested "leukocyte adhesion to vascular endothelial cell", so that each cell is specified in the GO term. For two cells of the same type, there are already terms such as "leukocyte aggregation".

Is this a reasonable short-term solution since it doesn't seem possible to be able to do this kind of statement using annotation extensions?

**Comment by rebeccafoulger** [comment]
For cell-cell signaling, we decided to use: 
has_start_location: CL:x
has_end_location: CL:y
see: https://github.com/geneontology/go-ontology/issues/12271

has_participant was suggested for the cell adhesion terms, to match some existing annotations in AmiGO (it's not consistent though, and has_participant isn't currently allowed as AE in Protein2GO).

**Comment by dosumis** [comment]
I don't see any logical problem with using has_participant for the cell adhesion case.

**Comment by cmungall** [comment]
@dosumis - it's just the homotypic case (X-X adhesion) we need to worry about, we need cardinality constraints to say `has-participant exactly 2 X`. But this is probably acceptable imprecision for AEs. So `+1` for has-participant

**Comment by rachhuntley** [comment]
OK, so my problem with allowing use of has_participant, as it stands now, in Protein2GO is that it's local_range is so wide. There is no local_range specified in the GitHub page for this relation, but it's child relations are as follows;
    has_input
    - has_direct_input
    - stabilizes
    has_output
    - results_in_formation_of
    has_regulation_target
    acts_on_population_of
    has_agent
    results_in_acquisition_of_features_of
    results_in_development_of
    results_in_division_of
    results_in_maturation_of
    results_in_morphogenesis_of
    results_in_movement_of
    transports_or_maintains_localization_of

Which encompasses pretty much all of the ranges you can think of. 

The problem we had before is that curators would be lazy and use has_participant for everything instead of finding the more appropriate child relation. By not having has_participant available it forces them to make a more specific and accurate statement. I believe that has_participant has always had this statement attached to it "Do not use this relation directly in annotation. Instead use one of the child terms."

So I don't see why we can't have another more specific child relation that allows use of only cell types?

Alternatively, could we use has_agent for cell-cell adhesion terms - since presumably both cell types have an active role in the adhesion process?

**Comment by rachhuntley** [comment]
To resume this thread, this was discussed in the 22nd March annotation call and there seemed to be some agreement that more specific relations could be beneficial, if only to guide curators to the most appropriate relation. These were the minutes;
- We discussed the merits of having a more specific child term of has_participant for terms like cell-cell adhesion
- Semantically, a more specific relation may not add anything, but more specific relations might help curators decide what is the appropriate relation to use
- Could rules be formulated in the GO_rel file to indicate how specific annotation extension relations can be used? 

Could we move forward on a decision for this? Can we create a more specific relation for use with cell-cell type terms that can only use a cell type identifier as entity?

@cmungall  @dosumis @RLovering

**Comment by dosumis** [comment]
On the narrow issue cell-cell adhesion:

> Alternatively, could we use has_agent for cell-cell adhesion terms - since presumably both cell types have an active role in the adhesion process?

I think this could be a reasonable compromise.

> - We discussed the merits of having a more specific child term of has_participant for terms like cell-cell adhesion
> - Semantically, a more specific relation may not add anything, but more specific relations might help curators decide what is the appropriate relation to use

I worry that there's no limit to proliferating relations just to restrict range.  It's also going to be hard to maintain the hierarchy - will have to be done by hand, but stay in sync with the classification of classes in the range.

> - Could rules be formulated in the GO_rel file to indicate how specific annotation extension relations can be used? 
- My concern is to get usage of relations in annotation extensions to be consistent with use in the ontology.  That way we maximise inference.  has_participant is widely used within the ontology, not just for cell-cell adhesion. If there are cases where extensions should follow a pattern where we use has_participant in the ontology, then well be back here discussing this issue again.
- This is not about rules so much as trying to get ontology editors and curators to follow consistent patterns.   In the longer term I think we need a way for curators to check for precedence in design patterns when making a decision about what relation to use.  This will also be needed for LEGO.

**Comment by rachhuntley** [comment]
OK, could we get a resolution on this and decide that we can use has_agent for cell-cell adhesion?
If so, we can bring this to the attention of curators on an annotation call.

**Comment by dosumis** [comment]
Fixed.  Usage statement for has_agent (AKA has active participant) extended to explicitly include cell adhesion:

"Use this relation to link a process to an entity that carries out that process. The entity may be a cellular component, a cell type or an anatomical structure. Examples include recording a vesicle type that mediates a transport process, a cell type that is the agent of a secretion process or a cell adhesion process..."
