### ISSUE TITLE
conflicting SP:KW UniProtKB-KW:KW-0336 & KW:KW-0812

### ISSUE THREAD

**Issue by ValWood** [geneontology/annotation_extensions#64]
O13960  Cell wall protein ecm33

Has conflicting SP:KW annotations
UniProtKB-KW:KW-0336
GO:0031225 - anchored component of membrane (cellular_component)
Definition: "The component of a membrane consisting of the gene products that are tethered to the membrane only by a covalently attached anchor, such as a lipid group that is embedded in the membrane. Gene products with peptide sequences that are embedded in the membrane are excluded from this grouping." [GOC:dos, GOC:mah]

and 
UniProtKB-KW:KW-0812
GO:0016021 - integral component of membrane (cellular_component) [QuickGO, AmiGO, BioPortal]
Definition: "The component of a membrane consisting of the gene products and protein complexes having at least some part of their peptide sequence embedded in the hydrophobic region of the membrane." [GOC:dos, GOC:go_curators]

**Comment by mah11** [comment]
wrong tracker - you want https://github.com/geneontology/go-annotation/issues (not annotation_extensions)

**Comment by ValWood** [comment]
whoops
