### ISSUE TITLE
Missing GOC documentation for some relations

### ISSUE THREAD

**Issue by ghost** [geneontology/annotation_extensions#67]
Hello, 
There is no GOC documentation for the following relations:
has_end_location
has_start_location
has_target_start_location
has_target_end_location

Thanks, Elena

**Comment by dosumis** [comment]
They have RO defs.  I can add usage statements - these will show up on QuickGO AE relations browser.

**Comment by mcourtot** [comment]
Elena refers to the link towards https://github.com/geneontology/annotation_extensions/tree/master/doc/has_target_end_location.md, which should be accessible from the QuickGO AE view at http://www.ebi.ac.uk/QuickGO/AnnotationExtensionRelations.html

![screen shot 2016-07-27 at 13 01 02](https://cloud.githubusercontent.com/assets/2214135/17174552/49d6a932-53fa-11e6-8173-9e2c073299b0.png)

Creating the missing md files would solve the issue; I'm just not sure how they are semi-automatically generated.

**Comment by dosumis** [comment]
Ahhh.  OK.  Seems like I did add usage statements. I'll re-run md gen script now.  There won't be anything much more than what you can see in the QuickGO pop-up though.

**Comment by dosumis** [comment]
Done
