### ISSUE TITLE
expansion of annotation domain for 'regulates-o-occurs-in' (expand to regulation of MF)

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/annotation_extensions#69]
Please could the annotation domain for ‘regulates-o-occurs-in’ be expanded to include ‘regulation of molecular function (GO:0065009)’. This fits with the ‘Usage’ statement, and I have a ‘regulation of enzyme activity’ term I need to use this relation with.

currently:
regulates_o_occurs_in
GO Annotation Domain: GO:0050789 (regulation of biological process)
GO Annotation Range: CARO:0000000 (anatomical entity) or CL:0000000 (cell) or GO:0005575 (cellular component) or GO:0005623 (cell) or GO:0032991 (macromolecular complex) or GO:0043234 (protein complex) or PO:0025131 (plant anatomical entity) or UBERON:0001062 (metazoan anatomical entity) or WBbt:0004017 (cell) or WBbt:0005766 (metazoan anatomical entity)
Usage: Use this relation to link a regulatory process or function to the structure that the regulated process or function occurs in.
Subsets:
cell_or_anatomical
cellular_component

Thank you!

**Comment by dosumis** [comment]
I've broadened to 'biological regulation', which is parent to both regulation of BP and regulation of MF.
