### ISSUE TITLE
has_agent - do we really need it for annotation extensions?

### ISSUE THREAD

**Issue by dosumis** [geneontology/annotation_extensions#7]
(Ticket extracted from notes written by @Rlovering & Rachael Huntley)
1. We don't think here is a need for has_agent, instead only a need for regulates_o_has_agent  

The has_agent usage seems to imply we can use this for a process, when actually it probably would only be used for the regulation of a process.    

For example you annotate protein A as being involved in the TCR signaling pathway, we don't think you are you going to use has_agent to list all the other proteins involved in the signaling pathway. However if you annotate protein B as being involved in regulating the TCR signaling pathway, you might want to use has_agent to document that protein B regulates this pathway by regulating the activity of protein A (which is annotated as involved in the signaling pathway).We think that in this case you would annotate protein B as being involved in regulating the TCR signaling pathway, and use regulates_o_has_agent protein A to specify how the TCR signaling pathway is being regulated by Protein B.

\2. Missing/incorrect information in range:
- GO Annotation Domain: GO:0003674 (molecular_function) or GO:0008150 (biological_process)  
- GO Annotation Range: CARO:0000000 (anatomical entity) or CL:0000000 (null) or GO:0005575 (cellular component) or GO:0005623 (cell) or PO:0025131 (plant anatomical entity) or UBERON:0001062 (metazoan anatomical entity) or WBbt:0004017 (null) or WBbt:0005766 (null)  
- Usage: The relationship that links an entity with a process in which the entity participates in the process by serving as the continuant that is responsible for the execution of the process.  

has_agent range is completely wrong and doesn't include Protein IDs.  
The usage statement for has_agent implies not to be used for reg of BP eg the agent we want to use is the kinase, which is not the protein responsible for the regulation of the kinase. And the continuant in the definition is most likely the protein (eg) you are actually annotating, not the proteins being regulated by the protein annotated.

**Comment by dosumis** [comment]
What about cases where the agent is not a gene product, but a cell component, cell, or anatomical structure?  In fact,  this applies to all current usage of has_agent

```
MGI  production of miRNAs involved in gene silencing by miRNA   has_agent(CL:0000057)   IMP PMID    16040801            
MGI F6UDT8  GO:0002369  T cell cytokine production  has_agent(CL:0000084)   IMP PMID    15699074
SWIS    Q5VZK9  GO:2000813  negative regulation of barbed-end actin filament capping    has_agent(GO:0008290)   ISS GO_REF  0000024 (F-actin capping protein complex)
```

In fact,  this applies to all current usage of has_agent: search in [AE_unrolled.tsv](https://raw.githubusercontent.com/geneontology/annotation_extensions/master/annotation_extension_usage_reports/AE_unrolled.tsv) for has_agent.

**Comment by cmungall** [comment]
Set `local_domain` to BP - there should never be an annotation extension with MF and has_agent some X, since the X is necessarily a complex or gene product, and this would be in the normal has_agent field

**Comment by dosumis** [comment]
> Set local_domain to BP - there should never be an annotation extension with MF and has_agent some X, since the X is necessarily a complex or gene product, and this would be in the normal has_agent field

Done.
